# Copyright (c) Jupyter Development Team.
# Distributed under the terms of the Modified BSD License.

---
version: "2"

services:
  notebook:
    build:
      context: .
      dockerfile: Dockerfile.notebook
#      args:
        # pip versioning:
#        DASHBOARDS_VER: '==0.6.*'
#        DECLWIDGETS_VER: '==0.7.*'
#        BUNDLER_VER: '==0.8.*'
    ports:
      - "8888:8888"
    depends_on:
      - dashboards
    links:
      - dashboards
    volumes:
      - work:/home/jovyan/work
    env_file: nb_secrets.env
    environment:
      DASHBOARD_SERVER_URL: http://dashboards:3000/
    restart: always

  dashboards:
    build:
      context: .
      dockerfile: Dockerfile.dashboards
#      args:
          # npm versioning:
#          DASHBOARDS_SERVER_VER: '@>=0.7.0 <0.8.0'
    ports:
      - "3000:3000"
    depends_on:
      - kernel_gateway
    links:
      - kernel_gateway
    env_file: db_secrets.env
    environment:
      PORT: 3000
      KERNEL_GATEWAY_URL: http://kernel_gateway:8888
    restart: always

  kernel_gateway:
    build:
      context: .
      dockerfile: Dockerfile.kernel
#      args:
        # pip versioning:
#        JUPYTER_KERNEL_GATEWAY_VER: '==0.5.1'
#        IPYWIDGETS_VER: '==5.1.*'
#        DECLWIDGETS_VER: '==0.7.*'
    environment:
      KG_ALLOW_ORIGIN: '*'
    restart: always

volumes:
  work:
